version=${project.version}
buildtime=${timestamp}
builder=${env.USERNAME}
builderName=${music.build.user.name}
builderEmail=${music.build.user.email}
buildhost=${env.COMPUTERNAME}
buildOs=${os.name}
gitBranch=${music.branch}
gitCommitIdDescribe=${music.commit.id.describe}
gitCommitId=${music.commit.id.full}
gitCommitUrl=${music.remote.origin.url}
gitCommitTime=${music.commit.time}
gitDirty=${music.dirty}